name: deploy to nest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: build and deploy
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          command_timeout: 3m
          script: |
            set +e
            cd nobelium
          
            git pull origin main
          
            rm -rf .next node_modules
          
            npm install
          
            npm run build
          
            if pm2 describe "nobelium" > /dev/null 2>&1; then
              PORT=8080 pm2 restart "nobelium" --update-env
            else
              PORT=8080 pm2 start npm --name "nobelium" -- run start
            fi
          
            pm2 save
          
            exit 0
